#!/bin/bash
#
# Copyright (C) 2013-2014 OpenMediaVault Plugin Developers
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

PLUGIN_DIR="/var/www/openmediavault/js/omv/module/admin/service"
MEDIA_DIR="${PLUGIN_DIR}/media/"

if [ ! -d "${MEDIA_DIR}" ]; then
    mkdir -p "${MEDIA_DIR}"
else
    rm -rf ${MEDIA_DIR}*
fi

# create node
cat <<EOF > "${MEDIA_DIR}Media.js"
// require("js/omv/WorkspaceManager.js")

OMV.WorkspaceManager.registerNode({
    id      : "media",
    path    : "/service",
    text    : _("Media"),
    icon16  : "images/tv.png",
    iconSvg : "images/tv.svg"
});
EOF

count=$(omv_config_get_count "//services/links/link")
index=1
disable_csp=0
while [ ${index} -le ${count} ]; do

    createtab=$(omv_config_get "//services/links/link[position()=${index}]/createtab")
    plugintab=$(omv_config_get "//services/links/link[position()=${index}]/plugintab")
    name=$(omv_config_get "//services/links/link[position()=${index}]/name")
    url=$(omv_config_get "//services/links/link[position()=${index}]/url")

    if [ ${createtab} != 0 ]; then
        disable_csp=1
        group=$(omv_config_get "//services/links/link[position()=${index}]/group")
        fileupper="${MEDIA_DIR}${group}.js"
        filelower="${MEDIA_DIR}${group}/${name}.js"

        if [ ! -f "${fileupper}" ]; then
            # create upper tab fileif not already created
            cat <<EOF > ${fileupper}
// require("js/omv/WorkspaceManager.js")
// require("js/omv/MediaManager.js")
// require("js/omv/workspace/tab/Panel.js")

Ext.define("OMV.module.admin.service.media.${group}", {
    extend : "OMV.workspace.tab.Panel",

    initComponent : function() {
        var me = this;
        var plugins = OMV.MediaManager.get("media", "${group}");
        me.items = [];
        Ext.Array.each(plugins, function(plugin) {
            me.items.push(Ext.create(plugin.className, {
                title : plugin.text
            }));
        });
        me.callParent(arguments);
    }
});

OMV.WorkspaceManager.registerPanel({
    id        : "${group}",
    path      : "/service/media",
    text      : "${group}",
    position  : ${index},
    className : "OMV.module.admin.service.media.${group}"
});

EOF
        fi

        # create directory for lower tab files
        if [ ! -d "${MEDIA_DIR}${group}" ]; then
            mkdir -p "${MEDIA_DIR}${group}"
        fi

        # Create lower tab file
        cat <<EOF > ${filelower}

// require("js/omv/MediaManager.js")
// require("js/omv/workspace/panel/Panel.js")

Ext.define("OMV.module.admin.service.media.${group}.${name}", {
    extend : "OMV.workspace.panel.Panel",

    initComponent: function() {
        var me = this;
        me.html = "<iframe src='${url}' width='100%' height='100%' />";
        me.callParent(arguments);
    }
});

OMV.MediaManager.register({
    ptype     : "media",
    id        : "${group}",
    text      : "${name}",
    position  : ${index},
    className : "OMV.module.admin.service.media.${group}.${name}"
});

EOF
    fi

    if [ ${plugintab} != 0 ]; then
        disable_csp=1
        service_dir_name=$(echo ${name} | tr '[:upper:]' '[:lower:]')

        if [ -d "${PLUGIN_DIR}/{service_dir_name}" ]; then

            # create upper tab fileif not already created
            cat <<EOF > "${PLUGIN_DIR}/{service_dir_name}/iframe.js"
// require("js/omv/WorkspaceManager.js")
// require("js/omv/workspace/panel/Panel.js")

Ext.define("OMV.module.admin.service.${service_dir_name}.iframe", {
    extend : "OMV.workspace.panel.Panel",

    initComponent : function() {
        this.html = "<iframe src='${url}' width='100%' height='100%' />";
        this.callParent(arguments);
    }
});

OMV.WorkspaceManager.registerPanel({
    id        : "iframe",
    path      : "/service/${service_dir_name}",
    text      : _("Web Client"),
    position  : 200,
    className : "OMV.module.admin.service.${service_dir_name}.iframe"
});

EOF
        fi
    fi

    index=$(( ${index} + 1 ))
done

chown -R openmediavault:openmediavault "${MEDIA_DIR}"

# Disable csp if iframes are used
if [ ${disable_csp} != 0 ]; then
    omv_set_default OMV_NGINX_SITE_WEBGUI_SECURITY_CSP_ENABLE 0
    omv_set_default OMV_NGINX_SITE_WEBGUI_SECURITY_XFRAMEOPTIONS_ENABLE false

    omv-mkconf nginx
    invoke-rc.d nginx restart
fi

omv_purge_internal_cache
